version: '3'

services:
  postgres:
    image: postgres:latest
    container_name: postgres_container
    environment:
        POSTGRES_DB: mydatabase
        POSTGRES_USER: myuser
        POSTGRES_PASSWORD: mypassword
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  pgadmin:
    image: dpage/pgadmin4:latest
    container_name: pgadmin_container
    environment:
        PGADMIN_DEFAULT_EMAIL: myuser@email.com
        PGADMIN_DEFAULT_PASSWORD: mypassword
    ports:
      - "5050:80"
    depends_on:
      - postgres

volumes:
  postgres_data:
