version: '3'

services:
  redis:
    image: redis
    container_name: redis
    ports:
      - "6379:6379"
  
  redis-commander:
    image: rediscommander/redis-commander
    container_name: redis-commander
    environment:
      - REDIS_HOSTS=local:redis:6379
    ports:
      - "8081:8081"
    depends_on:
      - redis
